### ISSUE TITLE
More distributed...

### ISSUE THREAD

**Issue by lardnicus** [lbryio/lbry-app#1004]
## The Issue
The current system is  centralised and open to being overtaken by a more advanced and decentralised implementation. It also uses wasteful PoW mining instead of allowing users to contribute those same resources to improving the speed and stability of the network.

### Expected behaviour
1. Content loads faster than YouTube
2. Users pay to store video on a distributed cloud with LBRY credits
3. Users are paid for views with LBRY tokens
4. The app should leverage encrypted, peer to peer bandwidth and hosting (ala MEGA) and reward users for contributing "proof-of-bandwidth" and "proof-of-storage" resources to the network in LBRY credits, instead of wasting those same resources doing PoW mining.

### Actual behaviour
1. Videos from the app are slow to arrive as they are hosted on centralised servers
2. The LBRY token comes from PoW mining

**Comment by tzarebczan** [comment]
@lardnicus thanks for submitting this issue!  

We are still a beta platform and still have lots of room to go in terms of improvements to our Peer to Peer network which serves up the files.  The point of LBRY is to allow publishers to control their data, which is why they host the content themselves (plus the servers we run to help with hosting) and it's also hosted by anyone that downloads the content - thus making it a decentralized file network.  Publishers are already paid per download if they set a price for their content.  We also have a mechanism to reward hosts for sharing data, but it currently disabled while we work out some optimizations.  

In terms of different mining schemes, can you provide more information on proof of bandwidth or proof of storage consensus mechanism?  The reason we went with PoW is because it's the best known and more secure consensus tool to date.

**Comment by lardnicus** [comment]
Thanks for the reply! I believe in the project although of course we all have different ideas about things...

Proof of storage (proof of capacity) is Burst coins claim to fame, but along with PoW, it is also a monumental waste of resources. For Burst, not turning GPU's into expensive fan heaters, but a manufacturing race to hell in locking up disk space.

That you are working on rewards for hosts is really great. Replacing PoW itself would be some next generation thinking but it could work along the lines of the client that requested and downloaded the video provides proof of receiving the file, who they received which parts of the file from and how fast it was delivered from each host. Hosts that can deliver a bigger variety of files faster will receive the lions share of new coins, hosts that can deliver more esoteric files will still be able to participate in "mining".

The ultimate dream of crypto today (of cuckoo cycle, of proof of capacity) It's a dream that anybody can participate in mining and distribution of the security of the network but as we continue to see each and every time, any automated process that is financially incentivised will be optimised and will centralise around ASICs etc...

The fact that you have real humans using the software to interact with the content I personally see as your biggest strength: "Proof of Human".

Will current miners be upset? Of course they are. Everywhere I preach this stuff I am met with huge pushback from PoW miners who are quite happy with the current situation.

PoW was a revolution, not saying it wasn't, but if LBRY has an offering that basically said "get paid to watch videos", and those videos were delivered faster than youtube... That's just as revolutionary, if not more so...

(Maybe then we can start talking about psychological colour theory and the LBRY green :)

**Comment by tzarebczan** [comment]
Closing this for now. We don't have any immediate plans to go away from POW, as this is the only proven consensus mechanism currently available. If you feel strongly about it, feel free to open an issue on https://github.com/lbryio/lbry
