### ISSUE TITLE
Ability to resend verification email

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1492]
## The Issue
Possibly related to https://github.com/lbryio/lbry-app/issues/997.

If a user begins the email verification process but never completes (doesn't go into email, get verification code), there is currently no way to re-send the email besides following the manual instructions to clear their login token. If they still have the old email, they can grab the verification code, but that will trigger a new email since it's expired, so they have to do it again. 

Instead, we should add a link to resend verification email on the verification input screen. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by amitnndn** [comment]
I am trying to take a dig at this one. @tzarebczan 

I understand that when a user first registers their email, there is a call to [LBRY API](https://api.lbry.io/user_email/new)'s ```user_email/new``` end point and since that one is for a new user, I am thinking that it should ideally create a conflict if I am trying to reuse the same funciton from the first step where the user enters their email for the first time. 

Is there any documentation available on what kind of API calls that I can use to resend the user email. I am thinking maybe changing the end-point will work, but I am not sure what the end point is. It would be great if you could point me to any documentation that is available or provide me with the actual end point.

Thanks!

**Comment by kauffj** [comment]
Hi @amitnndn! Thanks for taking this on.

You can call `/user_email/resend_token?email=xxx@example.com`.

This API is not publicly documented as it is primarily intended for our internal use.

**Comment by tiger5226** [comment]
solved and merged
