### ISSUE TITLE
Use Prettier

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#202]
## The Issue
Currently the js code has all sorts of different styles. (single/double quotes, semi/no-semi, tabs/spaces)

I think it would be beneficial to add Prettier to have a more unified code base. I also created a PR implementing it here: https://github.com/lbryio/lbry-app/pull/201

I am creating this issue to see what everyone thinks

**Comment by 6ea86b96** [comment]
I would love to see prettier integrated :+1:

**Comment by seanyesmunt** [comment]
I prefer tabs, but I know others will fight to use spaces. Maybe we could do a thumbs up/thumbs down on this comment to determine what to use?

Thumbs up: tabs
Thumbs down: spaces

**Comment by kauffj** [comment]
This is a good idea. Need to look into it a bit more, but expect a merge later today.

**Comment by filipnyquist** [comment]
I think this is a great idea and it will be needed now as more and more people contribute code!

**Comment by kauffj** [comment]
This is merged. I decided to keep spaces over tabs since I think it's more common, but I don't feel strongly about this. I also added trailing commas where supported by ES5 (objects, arrays), switched from single quotes to double quotes, since JSX will be all double quotes anyway, and fixed the monitor path to compile on push. 

@alexliebowitz @6ea86b96 @lyoshenka @jackrobison please:
1) Rebase any active branches to be on top of master to minimize later merge headaches.
2) Make sure that auto-formatting is working for you on your next commit.

**Comment by lyoshenka** [comment]
Are we really going with 80 chars per line max? Can we do something more reasonable, like maybe 120?
