### ISSUE TITLE
Publish button gets stuck when publishing multiple files in a row

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#22]
the client gets stuck  like this regularly when trying to publish multiple files in a row. I don't know if this is a bug or if it is on my side, but I could not see why it would be on my side.

![pasted image at 2017_03_24 12_40 am](https://cloud.githubusercontent.com/assets/362784/24321979/d19dbdee-1130-11e7-9782-d34500dbb9cc.png)

Uploads are completed before I attempt another.

It only happens after I publish 2 or 3 files. I  can cancel and retry

and another bug in the GUI: when trying to publish with a bid of 0, the user is notified that he must complete the bid field, but the button 'Publish' turns to 'Publishing' and is not accessible to the user, leaving him only the option of cancelling and going through the whole process again

Notify adir92 in Slack when it's fixed.

**Comment by alexliebowitz** [comment]
I think this bug can't happen in this specific form with the new fast publish system, since it always creates the entry in the publish cache--i.e. it doesn't wait for `publish` to return before it sends you to the My Files page.

It feels like this could be a lbrynet bug. @jackrobison: is there any reason that doing several publish attempts in succession could result in calls to `publish` ? Like, maybe there's a race condition if you publish a file while the last one is still being reflected? (Bear in mind this bug is from late March.)

Also, the Redux branch completely overhauls our state management through the whole app, so if this is somehow still happening and it's on the client side, there's a good chance Redux will make this go away on its own.
