### ISSUE TITLE
Timeout modal needs to be smarter

### ISSUE THREAD

**Issue by 6ea86b96** [lbryio/lbry-app#328]
## The Issue

If a load/download fails, and you are on a different file page, an error modal appears showing the name of the current file, not the one downloading

### Steps to reproduce
1. Try to download an unavailable file
2. Navigate to a different file
3. Wait

### Expected behaviour
An error modal should appear with the correct file details.

### Actual behaviour
An error modal appears with the current file details

**Comment by tzarebczan** [comment]
We definitely need some work on this as the current message is not informative. 

For instance, a failed download shows the sdhash
Error message: Failed to download 8a455fb52ac158ec8bb80737dd9dc1e70c25dcd7b6966bc358cc466b78fdcc22c646616ba3decdba906d27f06730ac49 within timeout

Users are not familiar with the SDhash, so the URL should be shown

**Comment by btzr-io** [comment]
@tzarebczan  url is also weird, what about -> `metadata.title`

**Comment by tzarebczan** [comment]
Yep, the title seems to make much more sense here, thanks for making that evident.

**Comment by tzarebczan** [comment]
@seanyesmunt / @liamcardenas - since https://github.com/lbryio/lbry/issues/883#issuecomment-348709033 now shows the URL, we should show that instead of the sd-hash. Ultimately I think we would want to show the title. 

Also, maybe we can simplify the popup - doesn't need to say "this error has been reported" but instead explain that it could not download the file at this time, please try again later. If they consistently see this error across multiple files, they should visit https://lbry.io/faq/unable-to-stream (I can beef this up to be more generic). Reasons for download failures could be DHT issues on our side, old content that was never properly seeded, or network issues on the users' side. 

When @6ea86b96 originally opened this ticket, I'm not sure if it was showing the incorrect file, maybe just some confusion there. But if you start download A, then go to claim B and while there, download A times out, it still shows the data for download A failure (and not download B as claimed in this ticket).
