### ISSUE TITLE
Stuck on connecting screen

### ISSUE THREAD

**Issue by midolegend2016** [lbryio/lbry-app#329]
First time to launch the app stuck on connecting screen for alot of time

**Comment by tzarebczan** [comment]
Please come over to #help for support on slack.lbry.io instead of opening an issue here. 

What os are you on? Are you on the latest version 0.13? Can try try restarting and then updating lbry to ensure all files are updated? 

If that doesn't work, can you post your lbrynet.log https://lbry.io/faq/lbry-directories

**Comment by midolegend2016** [comment]
i used both 0.12 and 0.13 same issue

**Comment by tzarebczan** [comment]
Sometimes the daemon does not update correctly if it's running in the background, so right now it's recommended to restart and then install update before starting lbry.

**Comment by kauffj** [comment]
@midolegend2016 please work with our support team so we can look into this, you can email @tzarebczan at help@lbry.io.

I'm going to close this.

**Comment by tzarebczan** [comment]
We actually took care of it via slack. A reboot and reinstall helped.
