### ISSUE TITLE
Negative balance after withdraw

### ISSUE THREAD

**Issue by samz-me** [lbryio/lbry-app#398]
## The Issue
Negative balance after withdraw
v0.14.0rc4

### Steps to reproduce
1. You have 9.9 LBRY
2. Try to withdraw 9 
3. Got error
4. Try to withdraw 7 
5. Balance in UI is equals "-3"

## System Configuration
![image](https://user-images.githubusercontent.com/2629338/28734041-a5bdf1ac-73e7-11e7-955e-f78e872a805b.png)

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Anything Else
It was updated to actual value after 

## Screenshots
![image](https://user-images.githubusercontent.com/2629338/28733999-71892ffa-73e7-11e7-953f-3ddc92d60f0f.png)

**Comment by tzarebczan** [comment]
Does it update shortly after? Temporarily the balance may show incorrectly due to the UXTO model that LBRY follows (same as Bitcoin).  When you send 7 LBC, you actually need to send the entire balance of your previous tx, which, let's say is 9LBC.  It then sends you back the 2 LBC as "change".  

Did you balance reflect accurately after a minute or two? 

Also, the reason your original amount failed is that the app forces you to leave 1LBC if withdrawing through the GUI.  If you use the CLI, you can withdraw the entire amount: https://lbryio.github.io/lbry/cli/

**Comment by samz-me** [comment]
Less then two. I understand that this is not critical issue.  I think you can change it to something like "pending" instead of negative value.

**Comment by kauffj** [comment]
This is a daemon issue, and I believe will be fixed when https://github.com/lbryio/lbry/pull/747 is merged/finished.
