### ISSUE TITLE
LBRY 14.3 does not auto-upgrade on Ubuntu 16.04

### ISSUE THREAD

**Issue by mzannoni** [lbryio/lbry-app#438]
## The Issue
After following the instruction to upgrade, nothing happened, the version is still 14.2 and it keeps asking me every time to upgrade.
I then downloaded the 14.3 package from GitHub, and I installed it with `apt-get`, not with the gnome software centre (it does not work with that).

### Steps to reproduce
1. Follow the link on the LBRY app first to dowload update, than to Upgrade
2. Nothing happens, until I manually close the LBRY window
3. Then, the gnome software centre starts, asking to install lbry 14.3
4. Nothing happens, except that gnome software centre restarts, asking to install 14.2
5. Click install, of course nothing happens, since 14.2 is already installed.
6. To successfully install 14.3, you need to use `apt-get`

### Expected behaviour
I should click the upgrade botton in the application and it should work.

### Actual behaviour
The window doesn't close automatically; after manually closing it, the gnome software centre does not install the new version correctly.

## System Configuration

 

Not very relevant, I didn't take this details before being able to fix the issue myself; reported here are the details of the correctly manually upgraded LBRY.

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID: 5rHZHZt64BVaEs9b2yrya7aRNGo4G3vArDvjqJdGBfkq13ZkBYZZ5HnUSL2RC3o4cn
- Operating system: Linux (Linux-4.4.0-89-generic-x86_64-with-Ubuntu-16.04-xenial)

**Comment by tzarebczan** [comment]
I was able to confirm this.
Another way to upgrade is via the deb file/terminal:
dpkg -i /path/to/deb/file.deb

**Comment by kauffj** [comment]
@tzarebczan can you try this again with the console open and see if the path to the deb is specified correctly?

The app calls `xdg-open` on this path to upgrade, so I suppose missing `xdg-open` could be the issue as well, but that should be on an Ubuntu install.

**Comment by tzarebczan** [comment]
Actually, I think it is working correctly but the issue may lie in Ubuntu Software Center.  I've tried a couple VMs and I've had issues just installing the deb file through the software center.  While doing some research, I found this http://www.omgubuntu.co.uk/2016/04/ubuntu-16-04-deb-software-install-error and associated Bug reports - many users having the same issue installing 3rd party deb files. I think the issue was fixed at some time and was recently re-introduced.  On a clean Ubuntu 16.04 release it would not install and even after doing all the updates, it still would not. Same thing actually happens in 17.04 too.

I went back to an old VM I had previously installed LBRY on (maybe 2/3 months ago) where I knew the software center was operational.  I added the log statement and it looks like the installeprath is pointing the correct location and it opens the correct deb file in Software Center:
`Checking for lbrynet daemon
lbrynet daemon is already running
Shutting down daemon
Update downloaded to /tmp/fxiJP6/LBRY_0.14.3_amd64.deb
The app will close, and you will be prompted to install the latest version of LBRY.
After the install is complete, please reopen the app.
Successfully stopped daemon via RPC call.
Quitting.
Launching upgrade installer at /tmp/fxiJP6/LBRY_0.14.3_amd64.deb
`
Software Center updates LBRY successfully after clicking install. 

Best bet for those having trouble with the installer is to run the install using the terminal:
dpkg -i /path/to/deb/file.deb
