### ISSUE TITLE
Auto-updating app

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#556]
I believe Electron supports it, so we ought to provide it.

**Comment by btzr-io** [comment]
https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

**Comment by alexliebowitz** [comment]
@kauffj 

On Tuesday we decided I would look into this. My findings:
  - It's just an interface to Squirrel, which is popular and well supported.
  - It appears that on Mac it's supposed to work out of the box.
  - The explanations for Windows are more vague, but it sounds like it may depend on using one of the standard Electron Windows installer packages. I think I remember us having some scary home-brew installer for Windows? I'll bring it up at the meeting tomorrow.
  - As to Linux, I see no way to do it, even with third party packages. Users are supposed to just configure their package manager to do auto updates. So it seems like we'll have to continue with the current system on Linux.
  - There are several release servers that support Squirrel. The appropriate one for us is probably [nuts](https://github.com/GitbookIO/nuts), because it's designed to do releases automatically off of a GitHub repo. It will require some configuration to tell it how our releases are tagged, and/or us changing how they're tagged, but otherwise theoretically it should work pretty much out of the box.

**Comment by kauffj** [comment]
... so @alexliebowitz want to do this for Win + Mac? :grinning:

**Comment by alexliebowitz** [comment]
I'll bite!

**Comment by finer9** [comment]
@kauffj are we still seeking a windev or does this cover it?

**Comment by finer9** [comment]
Do I need to find a windev?

**Comment by kauffj** [comment]
@finer9 no

**Comment by lyoshenka** [comment]
Related: https://github.com/lbryio/lbry-app/issues/298

**Comment by liamcardenas** [comment]
@alexliebowitz @lyoshenka will this PR fix https://github.com/lbryio/lbry-app/issues/298 ?

**Comment by lyoshenka** [comment]
possibly. 

for one, i don't know the standard way of making sure there's only one daemon process running at a time. in linux there are pidfiles and `pgrep`. idk how windows does it. 

once we figure that out, we need to make sure the daemon is stopped before the update starts.
