### ISSUE TITLE
Published file dialog won't display fully, gets stuck on loading then throws error.

### ISSUE THREAD

**Issue by Rob-pw** [lbryio/lbry-app#57]
![screen shot 2017-04-26 at 15 43 55](https://cloud.githubusercontent.com/assets/4596295/25440308/fdb69f84-2a96-11e7-9c27-b8ace171b479.png)

"I can't open my published file anymore since yesterday. It gets stuck on "loading" and then this error also occurred at one time. I can't fully display it - this is how it showed up."

**Comment by alexliebowitz** [comment]
Sorry we let this get buried. It looks like your daemon just crashed. That could happen for a bunch of reasons, and the stability of the daemon is improving over time in general, but we should probably have a specific modal/message for this instead of just an error dialog. Are you still getting this?

The bug with the modal displaying weirdly is fixed (#113).
