### ISSUE TITLE
Can't claim any reward - Wallet_address does not match user

### ISSUE THREAD

**Issue by chron0** [lbryio/lbry-app#683]
### Steps to reproduce
1. Trying to claim any reward

### Expected behaviour
Reward should be granted

### Actual behaviour
Error Message: Wallet_address does not match user

## System Configuration

 

- LBRY Daemon version: 0.17.0
- LBRY App version: 0.17.0
- LBRY Installation ID: 2BXqc5xEqfBfZmfzoH2Z8hQnpDnmTfkYhzF35BtktmrkRDX5hzoq3Tg9bb2nXVCRcn
- Operating system: Linux

## Anything Else

I've done email verification numerous times (always same email) over the past couple of weeks since lbry app always re-requested it. "Reward Eligible" is checked on help page.

**Comment by tzarebczan** [comment]
Can you send me your email address to help@lbry.io along with screenshots of the reward / transactions screen?

**Comment by chron0** [comment]
Sent, thanks in advance.

**Comment by tzarebczan** [comment]
Also, lbry should not re request the verification that many times. Are you using the same email on multiple installations? Or possible different emails that were once used on the same one? Move around any wallet 
 files?
 https://lbry.io/faq/lbry-directories

**Comment by chron0** [comment]
Yes, I do have lbry on my desktop and on my laptop (which doesn't seem like a totally special use case to me). Since I'm also mining I want to be able to use it on multiple hosts to check/access balance, just like any other blockchain based system. 

I've started back on 0.12. IIRC I've copied the wallet files because it didn't make sense to me to have two separate wallets. But it was always the same lbry client on the laptop that re-requested verification and I haven't used the desktop client for a long time.

**Comment by tzarebczan** [comment]
Going to close this and we'll take care of it via email. 

We don't recommend running the same wallet on multiple PCs, at least not concurrently. There may also be some discrepancies on one of the wallets when transactions are made on the other. LBRY works similar to bitcoin and because we use a light client (electron wallet), the wallet addresses it generates on each may be different (but still tied to your seed).  This may have caused some confusion in our rewards API side, I'll look into it.  

Also, if you sign in on one PC, it will force you to sign in again when you load it up on another PC (if using the same email). A way around this would be to use separate emails/wallets (I know you said you don't want to maintain two wallets).

**Comment by tzarebczan** [comment]
@chron0 Let me know when you get to end up checking out if the issue was fixed.

**Comment by chron0** [comment]
updated to lbry 0.17.1, cleared cache, re-done verification:

Rewards can be claimed and, I checked to test, cannot be
claimed more than one time (at least the single event ones).

It seems to be fixed, yay, thank you very much :)
