### ISSUE TITLE
Adopt Flow

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#684]
Types are nice.

**Comment by seanyesmunt** [comment]
What about Flow? Would be a lot easier to integrate incrementally.

**Comment by kauffj** [comment]
@seanyesmunt you and @liamcardenas should discuss this!

I've not worked with either personally, but having worked on long-standing applications, I've definitely shifted towards static typing and immutability as producing code that is easier to refactor and reason about.

**Comment by liamcardenas** [comment]
Hey guys, thanks for tagging me, @kauffj . I just finish the last day of my job Friday and will not be more available on github/slack/etc.

I agree, Flow is a good idea due to the ease of incremental integration. I am not sure about the relative merits of flow vs typescript-- although I think typescript's type system is much more powerful and, in the past, I have found flow all too easy to forget about/ignore.

I am not sure how hard it would be to port the code base to typescript, as regular js code *should* "just work" (although that is very unlikely). I will look more into this...

@seanyesmunt let's chat. I'll message you on slack.
