### ISSUE TITLE
LBRY app quits with daemon already running error 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#920]
## The Issue
This happens mostly between upgrades when the LBRY app is updated but the lbrynet-daemon process continues to run/get stuck in the background. When attempting to run LBRY, it looks like it's starting and then will close out with an "daemon unexpectly quit" error. In the logs, you see:

`2017-12-30 17:47:39,213 INFO     lbrynet.daemon.DaemonControl:65: lbrynet-daemon is already running`

This usually requires the daemon to be killed manually and LBRY restarted. Sometimes you can restart just the app and it picks it up the 2nd time. 

Sort of related to https://github.com/lbryio/lbry-app/issues/298 as that should shut down any running daemons. 

### Steps to reproduce
1. Get daemon stuck in background when closing LBRY (not easily reproducible)
2. Start LBRY
3. Notice error in log / LBRY app shuts down

## System Configuration

 

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.19.3
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
@IGassmann is this why you ended up killing the daemon? I should have been more specific in my original issue, but if you ran the daemon as a separate process before, the app would pick it up. This would work a majority of the time.  I think it only ran into problems between app upgrades - but if the daemon version is the same between different app versions, it should still use the running daemon (could the app check the version before killing it?)

**Comment by george-mcintyre** [comment]
I get this when installing LBRY for the first time.  I am a developer and I suspect there is some interaction with some of the SDKs I develop with.  

Error message "Daemon has Exited" "The daemon may have encountered an unexpected error, or another daemon instance is already running.  For more information please visit: 
https://lbry.com/faq/startup-troubleshooting"

- LBRY Version: 0.33.2
- OS: MacOS Mojave: 10.14.5
- Console output:
`Current system appearance, (HLTB: 2), (SLS: 1 
Post-registration system appearance: (HLTB: 2) 
NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 1
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600003feb840
 (
    "<NSAquaAppearance: 0x6000009f9fc0>",
    "<NSSystemAppearance: 0x6000009fa1c0>"
)>
nw_path_close_fd Failed to close guarded necp fd 37 [9: Bad file descriptor]
GVA info: preferred scaler idx 1
UNIX error exception: 17  [repeated 7 times]
skipping upgrade for locked keychain /Users/*****/Library/Keychains/1Password.keychain 
UNIX error exception: 17 
LSExceptions shared instance invalidated for timeout.
LSExceptions shared instance invalidated for timeout.
AggregateDictionary is not supported on this platform`

**Comment by kimi00jason** [comment]
Just a user... Got this the first time installing it. Just want to provide some data since ticket describe this was hard to reproduce.

2020-12-14 13:04:35,417 INFO     lbry.extras.daemon.daemon:501: RPC server listening on TCP ::1:5279
2020-12-14 13:04:35,418 ERROR    lbry.extras.daemon.daemon:514: media server failed to bind TCP localhost:5280
2020-12-14 13:04:35,419 INFO     lbry.extras.daemon.daemon:568: stopped api components
2020-12-14 13:04:35,419 INFO     lbry.extras.daemon.daemon:572: stopped api server
2020-12-14 13:04:35,419 INFO     lbry.extras.daemon.daemon:575: finished shutting down
2020-12-14 13:04:45,197 INFO     lbry.extras.daemon.daemon:485: Starting LBRYNet Daemon
2020-12-14 13:04:45,198 INFO     lbry.extras.daemon.daemon:487: Platform: {
  "processor": "Intel64 Family 6 Model 60 Stepping 3, GenuineIntel",
  "python_version": "3.7.4",
  "platform": "Windows-10-10.0.19041-SP0",
  "os_release": "10",
  "os_system": "Windows",
  "lbrynet_version": "0.86.1",
  "version": "0.86.1",
  "build": "release"
}

**Comment by roabhi** [comment]
Hi there. I am having this same issue after installing 0.52.0 on Mint 18.1 

Previous version was working just fine.  Tried `sudo sysctl kernel.unprivileged_userns_clone=1`, restarted computer and reinstalled package but no avail.

I get the following error from console

`Starting SDK
(node:7372) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Sandbox listening on port 5278.
Daemon: [7447] Error loading Python lib '/tmp/_MEIBbUvDj/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIBbUvDj/libpython3.7m.so.1.0)

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`

Any help is appreciated.

Thanks.
